# 指明依赖库的来源地址，不使用默认 CDN
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# 屏蔽所有第三方框架警告
inhibit_all_warnings!

target 'HQLTableViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HQLTableViewDemo
  
  # 网络模块
  pod 'AFNetworking'
  # pod 'AFNetworkActivityLogger', '~> 3.0.0'
  
  # 服务模块
  pod 'INTULocationManager'     # 位置服务模块
  
  # UI 类
  pod 'EAIntroView'             # 启动引导页、App 新功能展示页面
  pod 'DZNEmptyDataSet'
  pod 'MGSwipeTableCell'
  pod 'YMCitySelect'            # 城市选择器
  pod "TTGTagCollectionView"    # Tag 标签
  pod 'PPNumberButton'          # 商品数量加减按钮
  pod 'BEMCheckBox'
  pod 'JVFloatLabeledTextField'
  
  # TabBar
  pod 'CYLTabBarController'          # 默认不依赖Lottie
  pod 'CYLTabBarController/Lottie'   # 依赖Lottie库
  
  # HUD、Refresh、Alert 弹窗
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'Toast'
  
  # 图片
  pod 'SDWebImage', '~> 5.7.3'
  pod 'SDCycleScrollView'       # 图片轮播器
  
  # JSON 模型转换框架
  pod 'Mantle'
  pod 'GRMustache', '~> 7.3.2'  # HTML 模版引擎
  
  # 自动布局
  pod 'Masonry'
  pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
  
  # 工具类
  pod 'YYKit'
  pod 'JKCategories'
  pod 'Nimbus'
  pod 'RegexKitLite'                  # 正则表达式
  pod 'ChameleonFramework'            # 颜色
  pod 'DateTools'                     # 时间日期

end
