# 指明依赖库的来源地址，不使用默认 CDN
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'HQLTableViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HQLTableViewDemo
  
  # 网络模块
  pod 'AFNetworking'
  # pod 'AFNetworkActivityLogger', '~> 3.0.0'
  pod 'SDWebImage', '~> 5.7.3'
  
  # UI 类
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'EAIntroView'
  pod 'MGSwipeTableCell'
  pod 'SDCycleScrollView'       # 图片轮播器
  pod 'Toast'
  pod 'PPNumberButton'
    
  # JSON 模型转换框架
  pod 'Mantle'
  
  # 自动布局
  pod 'Masonry'
  
  # 工具类
  pod 'ChameleonFramework'
  pod 'DZNEmptyDataSet'
  pod 'YYKit'
  pod 'Nimbus'
  pod 'JKCategories'
  pod 'RegexKitLite'
  
  # TabBar
  pod 'CYLTabBarController'          # 默认不依赖Lottie
  pod 'CYLTabBarController/Lottie'   # 依赖Lottie库

end
