# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIStackView' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for UIStackView
  pod 'YYKit', '~> 1.0.9'
 
end
