# 指明依赖库的来源地址，不使用默认 CDN
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# 屏蔽所有第三方框架警告
inhibit_all_warnings!

target 'DataStorage' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for DataStorage
  
  # JSON 模型转换框架
  pod 'YYKit'
  pod 'Mantle'
  pod 'MJExtension'
  
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'JKCategories'
  pod 'SAMKeychain' # 钥匙串管理
  pod 'PINCache'    # 缓存
  
  # 数据库
  pod 'WCDB'
  pod 'FMDB'
  # pod 'FMDB/FTS'   # FMDB with FTS
  # pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
  # pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
  # pod 'FMDB/SQLCipher'   # FMDB with SQLCipher
  
  # 配置 Masonry Target 版本
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "Masonry"
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
              end
          end
      end
  end

end
