# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MYDropMenu_Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MYDropMenu_Example
  pod 'Masonry', '~> 1.0.2'  
  pod 'YYKit', '~> 1.0.9'

  target 'MYDropMenu_ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MYDropMenu_ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
