# 指明依赖库的来源地址，不使用默认 CDN
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# 屏蔽所有第三方框架警告
inhibit_all_warnings!

target 'UICollectionView' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for UICollectionView
  
  # 网络模块
  pod 'AFNetworking'
  pod 'YTKNetwork'
  pod 'SDWebImage'
  
  # UI 模块
  pod 'SDCycleScrollView'       # 图片轮播器
  
  # HUD、Refresh、Alert 弹窗
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'Toast'
  
  # 自动布局框架
  pod 'Masonry'
  pod 'CHTCollectionViewWaterfallLayout'
  
  # 工具组件类
  pod 'YYKit'
  pod 'JKCategories'
  pod 'ChameleonFramework'
  
  # 指定 Masonry Target 编译版本
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "Masonry"
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
              end
          end
      end
  end

end
