# 指明依赖库的来源地址，不使用默认 CDN
source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

platform :ios, '15.0'

target 'TwitterInstant' do
  pod 'ReactiveObjC', '~> 3.1.1'
  pod 'LinqToObjectiveC', '~> 2.1.0'
end

