# 指明依赖库的来源地址，不使用默认 CDN
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# 屏蔽所有第三方框架警告
inhibit_all_warnings!

target 'HQLCamera' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for HQLCamera
  # 网络模块
  pod 'AFNetworking'
  pod 'SDWebImage'
  
  # JSON 模型转换框架
  pod 'Mantle'
  
  # 自动布局框架
  pod 'Masonry'

  # 工具组件类
  pod 'YYKit'
  pod 'JKCategories'
  
  # 图片处理类
  pod 'HXPhotoPicker'   # 图片选择器
  pod 'RSKImageCropper' # 图片裁剪
  
  # 二维码扫描
  pod 'LBXScan/LBXNative'
  pod 'LBXScan/UI'

  # 指定 Masonry Target 编译版本
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "Masonry"
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
              end
          end
      end
  end
end
