# 指明依赖库的来源地址，不使用默认 CDN
source 'https://github.com/CocoaPods/Specs.git'

# 屏蔽所有第三方框架警告
inhibit_all_warnings!

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KeychainDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for KeychainDemo
  pod 'YYKit'
  pod 'Mantle'      # JSON 模型转换框架
  pod 'SAMKeychain' # 钥匙串管理
  pod 'MBProgressHUD'
  pod 'PINCache'    # 缓存
end
