# 指明依赖库的来源地址，不使用默认 CDN
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NavigationControllerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for NavigationControllerDemo
  
  pod 'ChameleonFramework'
  pod 'JKCategories'
  
  # 自动布局框架
  pod 'Masonry'
  
  pod "PYSearch"
end
