# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'PayDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayDemo

  # 网络模块
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'Reachability'

  # 服务模块
  pod 'AlipaySDK-iOS'
  pod 'WechatOpenSDK'

  # UI 模块
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'EAIntroView'
  pod 'DZNEmptyDataSet'
  pod 'XLForm'

  # 工具组件类
  pod 'ChameleonFramework'
  pod 'FDFullscreenPopGesture'
  pod 'IQKeyboardManager'
  pod 'YYKit'
  pod 'DateTools'
  pod 'UIAlertController+Blocks'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'Toast'

end
