# 指明依赖库的来源地址，不使用默认 CDN
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# 屏蔽所有第三方框架警告
inhibit_all_warnings!

target 'HQLTakePhotoDemo' do

    # JSON 模型转换框架
    pod 'Mantle'
    
    # 自动布局框架
    pod 'Masonry'
    
    # 图片选择器
    pod 'HXPhotoPicker'
    
    # 相机&二维码扫描
    pod 'LBXScan/LBXNative'
    pod 'LBXScan/UI'
    
    # 其他
    pod 'YYKit'
    pod 'RSKImageCropper'
    pod 'OpenCV-iOS'

    # 指定 Masonry Target 编译版本
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == "Masonry"
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
                end
            end
        end
    end
end
