# 指明依赖库的来源地址，不使用默认 CDN
# source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/mirrors/CocoaPods-Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'RWReactivePlayground' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for RWReactivePlayground
  pod 'ReactiveObjC', '~> 3.1.1'  

  target 'RWReactivePlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
