# 指明依赖库的来源地址，不使用默认 CDN
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# 屏蔽所有第三方框架警告
inhibit_all_warnings!

target 'CoreLocationDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for CoreLocationDemo
  pod 'INTULocationManager' # 位置服务模块
  pod 'Mantle' # JSON 模型转换框架
  pod 'Masonry' # 自动布局框架
  pod 'JKCategories'
  
  # 更改所有第三方框架 Target 版本
  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
  end

end
